name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Triggers when a new version tag (e.g., v1.0.0) is pushed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CUDA Toolkit
        run: |
          choco install cuda --version=10.2.89.20191206 -y
        shell: pwsh
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore BitCrack.sln

      - name: Build Solution
        run: msbuild BitCrack.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Find the built EXE
        run: |
          echo "BUILD_PATH=$(Get-ChildItem -Path x64/Release/clBitCrack.exe | Select-Object -ExpandProperty FullName)" >> $GITHUB_ENV
        shell: pwsh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}
          path: path/to/your/compiled/files


  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-exe
          path: release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
